version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my-custom-network

  flask-app:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./static_data:/app/static_data
    depends_on:
      - redis
    networks:
      - my-custom-network

networks:
  my-custom-network:
    driver: bridge